waypoints:
  filepath: /home/pilyang/wps/logs/wp_berlin_1.csv
  

driving:
  mu: 1
  max_look_ahead: 1.9
  min_look_ahead: 0.9
  max_speed : 6.0
  min_speed : 1.5
  manual_speed_control:
    mux_size: 0
    region_1:
      starting_wp : 0
      ending_wp : 120
      max_speed : 3.7
      min_speed : 3.0
    region_2:
      starting_wp : 121
      ending_wp : 300
      max_speed : 3.7
      min_speed : 3.0
    region_3:
      starting_wp : 301
      ending_wp : 330
      max_speed : 4.0
      min_speed : 3.0
    region_4:
      starting_wp : 331
      ending_wp : 530
      max_speed : 5.0
      min_speed : 4.3
    region_5:
      starting_wp : 531
      ending_wp : 570
      max_speed : 2.4
      min_speed : 1.3
    region_6:
      starting_wp : 571
      ending_wp : 720
      max_speed : 3.0
      min_speed : 2.0
    region_7:
      starting_wp : 721
      ending_wp : 750
      max_speed : 3.5
      min_speed : 2.0
    region_8:
      starting_wp : 751
      ending_wp : 900
      max_speed : 5.0
      min_speed : 4.3

# DP_angle_proportion should be under 1
tuning:
  DP_angle_proportion : 0.0
